# Mosquitto MQTT Broker 1 - Sensor ↔ Gateway layer
# Sensor Node publishes local/sensors/+/data here
# Gateway Node subscribes local/sensors/+/data here
listener 1883
allow_anonymous true

# Logging
log_type all
log_dest stdout

# Persistence
persistence true
persistence_location /mosquitto/data/
