# Mosquitto MQTT Broker - Dev Configuration
listener 1883
allow_anonymous true

# Logging
log_type all
log_dest stdout
log_dest topic

# Persistence
persistence true
persistence_location /mosquitto/data/
